branches:
  only:
    - master
    - develop
 
sudo: required
services:
  -docker

before_install:
  - docker build -t someone/client -f client/Dockerfile.dev ./client
  - docker build -t someone/api -f server/Dockerfile.dev ./server

script:
  - docker run -e CI=true someone/client npm run test
  - docker run -e CI=true someone/api python manage.py test
  - docker run -e CI=true someone/api pylint *