branches:
  only:
    - master
    - develop
 
sudo: required
services:
  -docker

before_install:
  - docker build -t someone/client -f client/Dockerfile.dev ./client
  - docker build -t someone/api -f server/Dockerfile.dev ./server

install:
  - sudo pip3 install pylint
script:
  - docker run -e CI=true someone/client npm run test
  - docker run -e CI=true someone/api python manage.py test && pylint server