branches:
  only:
    - master
    - develop
 
sudo: required
services:
  - docker

before_install:
  - docker build -t someone/client -f ./client/Dockerfile.dev ./client
  - docker build -t someone/api -f ./client/Dockerfile.dev ./client

script:
  - docker run someone/client npm run test
  - docker run someone/api python manage.py tests
  - docker run someone/api pylint *