sudo: required
services:
  -docker

before_install:
  - docker build -t someone/client -f Dockerfile.dev ./client
  - docker build -t someone/api -f Dockerfile.dev ./server

script:
  - docker run -e CI=true someone/client npm run test
  - docker run -e CI=true someone/api python manage.py test