branches:
  only:
    - master
    - develop
 
sudo: required
services:
  - docker

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install docker-compose

script:
  - docker-compose -f docker-compose-tests.yml run --rm client
  - docker-compose -f docker-compose-tests.yml run --rm api