version: '3'
services:
    api:
        build:
            context: server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/venv
            - ./server:/app
        command: >
            sh -c "python manage.py makemigrations &&
                   python manage.py runserver"
    client:
        build:
            context: client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        ports: 
            - "3000:3000"
        command: >
            sh -c "npm run start"